### ISSUE TITLE
PUA character's issue

### ISSUE THREAD

**Issue by wengxt** [scj2000/scj-tables#3]
Hi, we're trying to replace all PUA characters to their Unicode corresponding ones in https://github.com/fcitx/fcitx5-table-extra/

We almost finished all of them, only about ~100 characters in scj6 we don't know what they are.

Here's a fully list for them:
https://gist.github.com/wengxt/b736cd6101df155825bf8ed431393f62

Do you know if there's a font that is able to display them, or what are those characters? Thanks!

**Comment by quintusl** [comment]
Hi,

Thank you for your message and support of the input method.

The PUA characters are of ISO10646HK (previously HKSCS). You may get more information from http://www.iso10646hk.net/ and can be seen with a font at http://glyph.iso10646hk.net/chinese/download_001.jsp

I cannot find all of them from ordinary Han typefaces in Unicode. Attached is a PDF with the mentioned font of the list for your information. 
[pua_in_scj6.pdf](https://github.com/scj2000/scj-tables/files/14232498/pua_in_scj6.pdf)

Should you need any further information, please do not hesitate to reach out to me.
